// <auto-generated />
namespace Project2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class TestCurrent2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestCurrent2));
        
        string IMigrationMetadata.Id
        {
            get { return "201405101237598_TestCurrent2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
