// <auto-generated />
namespace Project2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _1405 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1405));
        
        string IMigrationMetadata.Id
        {
            get { return "201405141456474_1405"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
